name: Build and test project

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - 'deliveries/**'
      - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  buildtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: 'x64'
        cache: maven
    - name: Build and test with Maven
      run: mvn -B verify --file pom.xml
